//
//  EntrupyServerResponseCode.h
//  EntrupySDK
//
//  Created by Muhammad Waqas on 29/06/2022.
//

typedef NS_ENUM(NSUInteger, EntrupyServerResponseCode){
    SERVER_RESPONSE_SUCCESS = 0,
    SERVER_RESPONSE_NOINTERNET  = 1,
    SERVER_RESPONSE_SERVERERROR = 2,
    SERVER_RESPONSE_INTERNALERROR = 3,
    SERVER_RESPONSE_OTHER = 4,
    SERVER_RESPONSE_REQUEST_TIMEDOUT = 5,
    SERVER_RESPONSE_TOO_MANY_REQUESTS = 6,
    SERVER_RESPONSE_IMAGE_UPLOAD_ERROR = 7,
    SERVER_RESPONSE_USER_DENIED_PERMISSIONS = 8,
    SERVER_RESPONSE_USER_PARSING_ERROR = 9,
    SERVER_RESPONSE_CONNECTIONERROR = 10,
};
