#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef ENTRUPYSDK_SWIFT_H
#define ENTRUPYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <EntrupySDK/EntrupySDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="EntrupySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol EntrupyLoginDelegate;
@protocol EntrupyConfigDelegate;
@protocol EntrupyCaptureDelegate;
@protocol EntrupySearchDelegate;
@protocol EntrupyFlagDelegate;
@protocol EntrupyDetailViewDelegate;
@protocol EntrupyFlagViewDelegate;
@protocol EntrupyRetakeCaptureDelegate;
@protocol EntrupySearchRetakeDelegate;
@protocol EntrupyMarketEdgeDelegate;
@protocol EntrupyMarketEdgeViewDelegate;
@protocol EntrupyTheme;
/// Modern Swift facade for Entrupy SDK
/// Provides async/await APIs while maintaining backward compatibility with Objective-C delegates
/// IMPORTANT: This is the public-facing EntrupyApp class. During incremental migration,
/// it internally uses EntrupyApp_Legacy (the Objective-C implementation) for actual work.
/// After full migration, EntrupyApp_Legacy will be removed.
SWIFT_CLASS_NAMED("EntrupyApp")
@interface EntrupyApp : NSObject
/// Shared instance (backward compatible with Objective-C)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EntrupyApp * _Nonnull shared;)
+ (EntrupyApp * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Legacy singleton accessor (for Objective-C compatibility)
+ (EntrupyApp * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Legacy delegate properties for Objective-C compatibility
/// These are set by EntrupyApp.m and used for delegate callbacks
/// Using didSet to automatically forward delegates to legacyApp to ensure references are never lost
@property (nonatomic, weak) id <EntrupyLoginDelegate> _Nullable loginDelegate;
@property (nonatomic, weak) id <EntrupyConfigDelegate> _Nullable configDelegate;
@property (nonatomic, weak) id <EntrupyCaptureDelegate> _Nullable captureDelegate;
@property (nonatomic, weak) id <EntrupySearchDelegate> _Nullable searchDelegate;
@property (nonatomic, weak) id <EntrupyFlagDelegate> _Nullable flagDelegate;
@property (nonatomic, weak) id <EntrupyDetailViewDelegate> _Nullable detailViewDelegate;
@property (nonatomic, weak) id <EntrupyFlagViewDelegate> _Nullable flagViewDelegate;
@property (nonatomic, weak) id <EntrupyRetakeCaptureDelegate> _Nullable retakeCaptureDelegate;
@property (nonatomic, weak) id <EntrupySearchRetakeDelegate> _Nullable searchRetakeDelegate;
@property (nonatomic, weak) id <EntrupyMarketEdgeDelegate> _Nullable marketEdgeDelegate;
@property (nonatomic, weak) id <EntrupyMarketEdgeViewDelegate> _Nullable marketEdgeViewDelegate;
@property (nonatomic, strong) id <EntrupyTheme> _Nullable theme;
@property (nonatomic, copy) void (^ _Nullable backgroundTransferCompletionHandler)(void);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class UIViewController;
@class EntrupySearchQuery;
@class NSError;
@class EntrupyDetailViewConfiguration;
@class EntrupyMarketEdgeViewConfiguration;
@class UIApplication;
@interface EntrupyApp (SWIFT_EXTENSION(EntrupySDK))
/// Legacy: Login user with signed request (Objective-C compatible)
/// During migration: Calls Objective-C implementation in EntrupyApp.m
/// After migration: Uses new Swift authorization service
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param signedRequest Signed authorization request from backend
///
- (void)loginUserWithSignedRequest:(NSString * _Nonnull)signedRequest;
/// Legacy: Generate SDK authorization request (Objective-C compatible)
///
/// returns:
/// Authorization request string to be signed by backend
- (NSString * _Nonnull)generateSDKAuthorizationRequest SWIFT_WARN_UNUSED_RESULT;
/// Legacy: Check if authorization is valid (Objective-C compatible)
///
/// returns:
/// true if authorization token is valid
- (BOOL)isAuthorizationValid SWIFT_WARN_UNUSED_RESULT;
/// Legacy: Fetch configuration type (Objective-C compatible)
/// During migration: Calls Objective-C implementation
/// After migration: Uses new Swift configuration service
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param configType Configuration type (production or debug)
///
- (void)fetchConfigurationType:(EntrupyConfigType)configType;
/// Legacy: Start capture for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param item Dictionary containing item metadata
///
/// \param viewController View controller to present capture workflow
///
- (void)startCaptureForItem:(NSDictionary<NSString *, id> * _Nonnull)item viewController:(UIViewController * _Nonnull)viewController;
/// Legacy: Search submissions (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param pageCursor Cursor for pagination
///
/// \param filters Search filters array
///
/// \param startDate Start date (0 to omit)
///
/// \param endDate End date (0 to omit)
///
/// \param paginationLimit Number of items per page (max 25)
///
- (void)searchSubmissionsAt:(NSArray * _Nonnull)pageCursor filters:(NSArray * _Nonnull)filters startDate:(NSTimeInterval)startDate endDate:(NSTimeInterval)endDate paginationLimit:(NSInteger)paginationLimit;
/// Searches authentication items using date ranges and customizable filters.
/// Depending on the selected result mode, the response returns either paginated full item history or aggregate counts only.
/// This method provides a flexible way to query authentication results with various filter options.
/// The response is paginated and can be configured to return full result objects or just counts.
/// <h2>Response Model</h2>
/// The result dictionary can be decoded into <code>EntrupySearchItemsResult</code>:
/// <ul>
///   <li>
///     <code>metadata</code>: Contains <code>result_mode</code> (<code>.results</code> or <code>.countOnly</code>)
///   </li>
///   <li>
///     <code>total_count</code>: Total number of items matching the query
///   </li>
///   <li>
///     <code>item_count</code>: Number of items in the current page
///   </li>
///   <li>
///     <code>items</code>: Array of <code>EntrupyCaptureResult</code> objects (nil when using <code>.countOnly</code>)
///   </li>
///   <li>
///     <code>next_cursor</code>: Cursor for fetching the next page (nil if last page)
///   </li>
/// </ul>
/// <h2>Filter Examples</h2>
/// \code
/// filters: [
///     .status([.authentic, .underReview]),
///     .brands(["louis_vuitton", "gucci"]),
///     .category([.luxury, .apparel]),
///     .flag([.flagged])
/// ]
///
/// \endcode<h2>Usage Example</h2>
/// \code
/// guard EntrupyApp.sharedInstance().isAuthorizationValid() else { return }
///
/// // pagination state
/// var nextPageCursor: String? = nil
///
/// let query = EntrupySearchQuery(
///     dateRange: .last(days: 7),
///     filters: [
///         .status([.authentic]),
///         .category([.luxury, .apparel])
///     ],
///     resultMode: .results,  // or .countOnly
///     limit: 20,
///     cursor: nextPageCursor
/// )
///
/// EntrupyApp.sharedInstance().searchAuthenticationItems(query: query) { result, error in
///     guard let result = result,
///           let data = try? JSONSerialization.data(withJSONObject: result),
///           let searchResult = try? JSONDecoder().decode(EntrupySearchItemsResult.self, from: data)
///     else {
///         return
///     }
///     
///     print("Total: \(searchResult.total_count)")
///     if let items = searchResult.items {
///         // Process items
///     }
///
///    // Persist cursor for next page if available
///    nextPageCursor = searchResult.next_cursor
/// }
///
/// \endcodenote:
/// The product category filter is required for results.
/// For additional details on search and filtering, please refer to the  <a href="https://developer.entrupy.com/docs/mobile-sdks/ios/sdk-reference/direct-access-api-guides/programmatic-search-items">Entrupy iOS SDK Documentation</a>
/// \param query Search query with dateRange, filters, resultMode, limit, and cursor
///
/// \param completion Handler called with result dictionary or error
///
- (void)searchAuthenticationItemsWithQuery:(EntrupySearchQuery * _Nonnull)query completion:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))completion;
/// Legacy: Get flag details for result (Objective-C compatible)
/// This method calls the legacy Objective-C implementation which uses completion handlers.
/// For Swift callers, the dictionary is automatically bridged from NSDictionary to [AnyHashable: Any]?.
/// \param entrupyID Entrupy ID of the result
///
/// \param completionHandler Completion handler with details dictionary or error
///
- (void)getFlagDetailsForResultWithEntrupyID:(NSString * _Nonnull)entrupyID completionHandler:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))completionHandler;
/// Legacy: Set flag for result (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param flag true to set flag, false to clear
///
/// \param entrupyID Entrupy ID of the result
///
/// \param flagReasonId ID of the flag reason
///
/// \param message Optional message for the flag
///
- (void)setFlag:(BOOL)flag forResultWithEntrupyID:(NSString * _Nonnull)entrupyID flagReasonId:(NSString * _Nonnull)flagReasonId message:(NSString * _Nullable)message;
/// Legacy: Display detail view for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// The delegate set on the Swift facade is forwarded to the legacy implementation.
/// \param entrupyID Entrupy ID of the item
///
/// \param configuration View configuration options
///
- (void)displayDetailViewForItemWithEntrupyID:(NSString * _Nonnull)entrupyID withConfiguration:(EntrupyDetailViewConfiguration * _Nonnull)configuration;
/// Presents the Market Edge view for a specific authentication result.
/// @param entrupyID The Entrupy ID for the item to display.
/// @param viewConfiguration Configuration options, including:
/// - displayMarketGrade: Show/hide market grade
/// - displayMarketValue: Show/hide market value
/// - displayMarketMatch: Show/hide market match
/// - displayRegionSelection: Show/hide region selection
/// @note The view is Presented modally over the current top view controller.
/// \code
/// guard EntrupyApp.sharedInstance().isAuthorizationValid() else {
///     print("User not authorized. Cannot display Market Edge view.")
///     return
/// }
///
/// let configuration = EntrupyMarketEdgeViewConfiguration(
///     displayMarketGrade: true,
///     displayMarketValue: true,
///     displayMarketMatch: true,
///     displayRegionSelection: true
/// )
///
/// //Implement EntrupyMarketEdgeViewDelegate to receive presentation callbacks.
/// EntrupyApp.sharedInstance().marketEdgeViewDelegate = self
/// EntrupyApp.sharedInstance().displayMarketEdgeViewForItem(withEntrupyID: entrupyID, withConfiguration: configuration)
///
/// \endcode
- (void)displayMarketEdgeViewForItemWithEntrupyID:(NSString * _Nonnull)entrupyID withConfiguration:(EntrupyMarketEdgeViewConfiguration * _Nonnull)configuration;
/// Legacy: Display flag view for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// The delegate set on the Swift facade is forwarded to the legacy implementation.
/// \param entrupyID Entrupy ID of the result
///
- (void)displayFlagViewForItemWithEntrupyID:(NSString * _Nonnull)entrupyID;
/// Legacy: Start retake capture for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// The delegate set on the Swift facade is forwarded to the legacy implementation.
/// \param entrupyID Entrupy ID of the item requiring retake
///
- (void)startRetakeCaptureForItemWithEntrupyID:(NSString * _Nonnull)entrupyID;
/// Legacy: Search retakes (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
- (void)searchRetakes;
/// Fetches MarketEdge data for a given Entrupy ID.
/// This API retrieves MarketEdge information associated with an authentication result.
/// The response can be decoded into the SDK provided <code>EntrupyMarketEdge</code> model, which
/// represents a consolidated data for an item.
/// <code>EntrupyMarketEdge</code> includes:
/// important:
/// Ensure the user is logged in before invoking this API.
/// <ul>
///   <li>
///     <code>identifier</code>: Authentication identifiers for the item.
///   </li>
///   <li>
///     <code>market_grade</code>: Condition rating based on submitted images, including rating details,
///     item report information, and region-level descriptions (<code>EntrupyMarketGrade</code>).
///   </li>
///   <li>
///     <code>market_value</code>: Estimated market value derived from recent market data, including
///     price and currency (<code>EntrupyMarketValue</code>).
///   </li>
///   <li>
///     <code>market_match</code>: Recent marketplace listings similar to the submitted item, such as
///     brand, style, and price (<code>EntrupyMarketMatch</code>).
///   </li>
///   <li>
///     <code>disclaimer</code>: Disclaimer text associated with MarketGrade and MarketValue.
///   </li>
///   <li>
///     <code>error</code>: Error information when MarketEdge data is unavailable.
///   </li>
/// </ul>
/// <h3>Usage Example</h3>
/// \code
/// // Assign the delegate
/// entrupyApp.marketEdgeDelegate = self
///
/// // Request MarketEdge data
/// entrupyApp.fetchMarketEdgeForItem(withEntrupyID: entrupyID)
///
/// // Handle success
/// func didFetchMarketEdgeCompleteSuccessfully(
///     _ response: [AnyHashable: Any],
///     forEntrupyID entrupyID: String
/// ) {
///     do {
///         let data = try JSONSerialization.data(withJSONObject: response, options: [])
///         let marketEdge = try JSONDecoder().decode(EntrupyMarketEdge.self, from: data)
///
///           // Check for MarketEdge level error
///           if let error = marketEdge.error {
///             // Handle MarketEdge error
///             return
///         }
///
///         // Access MarketEdge properties
///         let identifier = marketEdge.identifier
///         let marketGrade = marketEdge.market_grade
///         let marketValue = marketEdge.market_value
///         let marketMatch = marketEdge.market_match
///         let disclaimer = marketEdge.disclaimer
///         
///
///         // Use the parsed data to populate UI or business logic
///     } catch {
///         // Handle decoding errors
///     }
/// }
///
/// // Handle failure
/// func didFetchMarketEdgeFailWithError(
///     _ errorCode: EntrupyErrorCode,
///     description: String,
///     localizedDescription: String,
///     forEntrupyID entrupyID: String
/// ) {
///     // Access the error code and localized description for failure cases
/// }
///
///
/// \endcode\param entrupyID The Entrupy authentication ID for which MarketEdge data should be fetched.
///
- (void)fetchMarketEdgeForItemWithEntrupyID:(NSString * _Nonnull)entrupyID;
/// Legacy: Cleanup user data (Objective-C compatible)
/// This method calls the legacy Objective-C implementation.
- (void)cleanup;
/// Legacy: Intercept application background URL session (Objective-C compatible)
/// During migration: Calls Objective-C implementation
/// \param application UIApplication instance
///
/// \param identifier URL session identifier
///
/// \param completionHandler Completion handler
///
- (void)interceptApplication:(UIApplication * _Nonnull)application handleEventsForBackgroundURLSession:(NSString * _Nonnull)identifier completionHandler:(void (^ _Nonnull)(void))completionHandler;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, EntrupyButtonBackgroundState, "EntrupyButtonBackgroundState", open) {
  EntrupyButtonBackgroundStateTapToCapture = 0,
  EntrupyButtonBackgroundStateBlurDetectionOn = 1,
  EntrupyButtonBackgroundStateMoveCloser = 2,
  EntrupyButtonBackgroundStateHandSteady = 3,
  EntrupyButtonBackgroundStateTapInsideToCapture = 4,
  EntrupyButtonBackgroundStateAutoCaptureActivated = 5,
  EntrupyButtonBackgroundStateNotDetected = 6,
  EntrupyButtonBackgroundStateNotInCenter = 7,
  EntrupyButtonBackgroundStateTooFar = 8,
  EntrupyButtonBackgroundStateMoveFar = 9,
};

@class NSCoder;
SWIFT_CLASS_NAMED("EntrupyCaptureButton")
@interface EntrupyCaptureButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setButtonBackgroundState:(enum EntrupyButtonBackgroundState)state;
- (enum EntrupyButtonBackgroundState)currentState SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC10EntrupySDK30EntrupyDetailViewConfiguration")
@interface EntrupyDetailViewConfiguration : NSObject
- (nonnull instancetype)initWithDisplayTimeline:(BOOL)displayTimeline displayUploadedImages:(BOOL)displayUploadedImages enableFlagging:(BOOL)enableFlagging enableItemDetailEdit:(BOOL)enableItemDetailEdit OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ObjcEntrupyEventName, "EntrupyEventName", open) {
  ObjcEntrupyEventNameCaptureStarted = 1,
  ObjcEntrupyEventNameCaptureSucceeded = 2,
  ObjcEntrupyEventNameCaptureFailed = 3,
  ObjcEntrupyEventNameCaptureCancelled = 4,
  ObjcEntrupyEventNameCaptureTimeout = 5,
  ObjcEntrupyEventNameRetakeStarted = 6,
  ObjcEntrupyEventNameRetakeSucceeded = 7,
  ObjcEntrupyEventNameRetakeCancelled = 8,
  ObjcEntrupyEventNameRetakeFailed = 9,
  ObjcEntrupyEventNameRetakeTimeout = 10,
  ObjcEntrupyEventNameAuthenticationBeginRequestSucceeded = 11,
  ObjcEntrupyEventNameAuthenticationCompleteRequestSucceeded = 12,
  ObjcEntrupyEventNameAuthenticationFetchRequestSucceeded = 13,
  ObjcEntrupyEventNameRetakeBatchRequestSucceeded = 14,
  ObjcEntrupyEventNameErrorOccurred = 15,
  ObjcEntrupyEventNameFullImageGuideButtonTap = 16,
  ObjcEntrupyEventNamePopupInstructionDoNotShowAgainCheckboxTap = 17,
  ObjcEntrupyEventNameRegionImageGuideButtonTap = 18,
  ObjcEntrupyEventNameFreshChatButtonTap = 19,
  ObjcEntrupyEventNameCertificateShareButtonTap = 20,
  ObjcEntrupyEventNameCertificateDownloadButtonTap = 21,
  ObjcEntrupyEventNameCertificateWebButtonTap = 22,
  ObjcEntrupyEventNameInvalidQrCode = 23,
  ObjcEntrupyEventNameGenericOcrSuccess = 24,
  ObjcEntrupyEventNameGenericOcrError = 25,
  ObjcEntrupyEventNameGenericOcrVerificationPopupShown = 26,
  ObjcEntrupyEventNameGenericOCRNoTextDetected = 27,
  ObjcEntrupyEventNameRfidScanError = 28,
  ObjcEntrupyEventNameRfidScanStarted = 29,
  ObjcEntrupyEventNameRfidScanSuccess = 30,
  ObjcEntrupyEventNameRfidScanCanceled = 31,
  ObjcEntrupyEventNameHistoryTimelineNoEventsFound = 32,
  ObjcEntrupyEventNameNotificationSignInSuccess = 33,
  ObjcEntrupyEventNameNotificationError = 34,
  ObjcEntrupyEventNameNotificationPushTokenRegistrationSuccess = 35,
  ObjcEntrupyEventNameNotificationSignInMaxRetryReached = 36,
  ObjcEntrupyEventNameNotificationJWTTokenExpired = 37,
  ObjcEntrupyEventNameUploadStarted = 38,
  ObjcEntrupyEventNameUploadSuccess = 39,
  ObjcEntrupyEventNameUploadError = 40,
  ObjcEntrupyEventNameMarketEdgeButtonTap = 41,
  ObjcEntrupyEventNameMarketGradeViewReportButtonTap = 42,
  ObjcEntrupyEventNameMarketMatchViewAllButtonTap = 43,
  ObjcEntrupyEventNameMarketMatchViewListingButtonTap = 44,
  ObjcEntrupyEventNameMarketEdgeRegionChangeButtonTap = 45,
  ObjcEntrupyEventNameMarketEdgeDisclaimerTap = 46,
  ObjcEntrupyEventNameMarketEdgeRefresh = 47,
  ObjcEntrupyEventNameMarketEdgeError = 48,
  ObjcEntrupyEventNameMarketEdgeStatus = 49,
  ObjcEntrupyEventNameMarketEdgeScreenExit = 50,
  ObjcEntrupyEventNameHistoryItemTap = 51,
  ObjcEntrupyEventNameInboxItemTap = 52,
  ObjcEntrupyEventNameViewCertificateButtonTap = 53,
  ObjcEntrupyEventNameViewTimelineButtonTap = 54,
  ObjcEntrupyEventNameViewDetailsButtonTap = 55,
  ObjcEntrupyEventNameNetworkLog = 56,
  ObjcEntrupyEventNameAuthenticationBeginRequestFailure = 57,
  ObjcEntrupyEventNameLogging = 58,
};

SWIFT_CLASS_NAMED("EntrupyLocalizationManager")
@interface ObjcEntrupyLocalizationManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10EntrupySDK34EntrupyMarketEdgeViewConfiguration")
@interface EntrupyMarketEdgeViewConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDisplayMarketGrade:(BOOL)displayMarketGrade displayMarketValue:(BOOL)displayMarketValue displayMarketMatch:(BOOL)displayMarketMatch displayRegionSelection:(BOOL)displayRegionSelection OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
SWIFT_CLASS("_TtC10EntrupySDK38EntrupyMarketGradeDetailViewController")
@interface EntrupyMarketGradeDetailViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@interface EntrupyMarketGradeDetailViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDelegate>
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UITableViewCell;
@interface EntrupyMarketGradeDetailViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC10EntrupySDK33EntrupyMarketGradeDetailViewModel")
@interface EntrupyMarketGradeDetailViewModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10EntrupySDK32EntrupyMarketMatchViewController")
@interface EntrupyMarketMatchViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface EntrupyMarketMatchViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@interface EntrupyMarketMatchViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDelegate>
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC10EntrupySDK18EntrupySearchQuery")
@interface EntrupySearchQuery : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_PROTOCOL("_TtP10EntrupySDK12EntrupyTheme_")
@protocol EntrupyTheme
@property (nonatomic, readonly, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nullable foregroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nullable borderColor;
@end

enum EntrupyZoomButtonBackgroundState : NSInteger;
SWIFT_CLASS_NAMED("EntrupyZoomButton")
@interface EntrupyZoomButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setButtonBackgroundState:(enum EntrupyZoomButtonBackgroundState)state;
- (enum EntrupyZoomButtonBackgroundState)currentBackgroundState SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, EntrupyZoomButtonBackgroundState, "EntrupyZoomButtonBackgroundState", open) {
  EntrupyZoomButtonBackgroundStateZoomIn = 0,
  EntrupyZoomButtonBackgroundStateZoomOut = 1,
};

@protocol ObjCSnapIQDelegate;
@class ObjCSnapIQResult;
SWIFT_CLASS_NAMED("SnapIQ")
@interface ObjCSnapIQ : NSObject
@property (nonatomic, readonly) BOOL isModelReady;
/// Delegate to receive detection results
@property (nonatomic, weak) id <ObjCSnapIQDelegate> _Nullable delegate;
/// Parameters:
/// <ul>
///   <li>
///     viewSize: The size of the view where boxes will be displayed
///   </li>
///   <li>
///     regionType: The type of region to detect and filter
///   </li>
///   <li>
///     isUltraWideEnabled: Whether ultra-wide lens is enabled for capture
///   </li>
///   <li>
///     completion: Callback to handle model loading results
///   </li>
/// </ul>
- (nonnull instancetype)initWithViewSize:(CGSize)viewSize regionType:(NSString * _Nonnull)regionType isUltraWideEnabled:(BOOL)isUltraWideEnabled completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion OBJC_DESIGNATED_INITIALIZER;
- (void)updateViewSize:(CGSize)newSize;
/// Process a camera frame and perform detection
/// \param sampleBuffer The camera frame buffer to process
///
///
/// returns:
/// A SnapIQResult containing the detected box and auto-capture analysis
- (ObjCSnapIQResult * _Nonnull)processFrameWithSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isRegionSupportedWithBrandName:(NSString * _Nonnull)brandName regionName:(NSString * _Nonnull)regionName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Delegate protocol for receiving SnapIQ detection results
SWIFT_PROTOCOL_NAMED("SnapIQDelegate")
@protocol ObjCSnapIQDelegate
- (void)didProcessFrameWithResult:(ObjCSnapIQResult * _Nonnull)result;
@end

/// Combined result containing both detected box and auto-capture analysis
SWIFT_CLASS_NAMED("SnapIQResult")
@interface ObjCSnapIQResult : NSObject
@property (nonatomic, readonly) BOOL shouldCapture;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly) float confidence;
@property (nonatomic, readonly) double fps;
@property (nonatomic, readonly) double inferenceTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef ENTRUPYSDK_SWIFT_H
#define ENTRUPYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <EntrupySDK/EntrupySDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="EntrupySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol EntrupyLoginDelegate;
@protocol EntrupyConfigDelegate;
@protocol EntrupyCaptureDelegate;
@protocol EntrupySearchDelegate;
@protocol EntrupyFlagDelegate;
@protocol EntrupyDetailViewDelegate;
@protocol EntrupyFlagViewDelegate;
@protocol EntrupyRetakeCaptureDelegate;
@protocol EntrupySearchRetakeDelegate;
@protocol EntrupyMarketEdgeDelegate;
@protocol EntrupyMarketEdgeViewDelegate;
@protocol EntrupyTheme;
/// Modern Swift facade for Entrupy SDK
/// Provides async/await APIs while maintaining backward compatibility with Objective-C delegates
/// IMPORTANT: This is the public-facing EntrupyApp class. During incremental migration,
/// it internally uses EntrupyApp_Legacy (the Objective-C implementation) for actual work.
/// After full migration, EntrupyApp_Legacy will be removed.
SWIFT_CLASS_NAMED("EntrupyApp")
@interface EntrupyApp : NSObject
/// Shared instance (backward compatible with Objective-C)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EntrupyApp * _Nonnull shared;)
+ (EntrupyApp * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Legacy singleton accessor (for Objective-C compatibility)
+ (EntrupyApp * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Legacy delegate properties for Objective-C compatibility
/// These are set by EntrupyApp.m and used for delegate callbacks
/// Using didSet to automatically forward delegates to legacyApp to ensure references are never lost
@property (nonatomic, weak) id <EntrupyLoginDelegate> _Nullable loginDelegate;
@property (nonatomic, weak) id <EntrupyConfigDelegate> _Nullable configDelegate;
@property (nonatomic, weak) id <EntrupyCaptureDelegate> _Nullable captureDelegate;
@property (nonatomic, weak) id <EntrupySearchDelegate> _Nullable searchDelegate;
@property (nonatomic, weak) id <EntrupyFlagDelegate> _Nullable flagDelegate;
@property (nonatomic, weak) id <EntrupyDetailViewDelegate> _Nullable detailViewDelegate;
@property (nonatomic, weak) id <EntrupyFlagViewDelegate> _Nullable flagViewDelegate;
@property (nonatomic, weak) id <EntrupyRetakeCaptureDelegate> _Nullable retakeCaptureDelegate;
@property (nonatomic, weak) id <EntrupySearchRetakeDelegate> _Nullable searchRetakeDelegate;
@property (nonatomic, weak) id <EntrupyMarketEdgeDelegate> _Nullable marketEdgeDelegate;
@property (nonatomic, weak) id <EntrupyMarketEdgeViewDelegate> _Nullable marketEdgeViewDelegate;
@property (nonatomic, strong) id <EntrupyTheme> _Nullable theme;
@property (nonatomic, copy) void (^ _Nullable backgroundTransferCompletionHandler)(void);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class UIViewController;
@class EntrupySearchQuery;
@class NSError;
@class EntrupyDetailViewConfiguration;
@class EntrupyMarketEdgeViewConfiguration;
@class UIApplication;
@interface EntrupyApp (SWIFT_EXTENSION(EntrupySDK))
/// Legacy: Login user with signed request (Objective-C compatible)
/// During migration: Calls Objective-C implementation in EntrupyApp.m
/// After migration: Uses new Swift authorization service
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param signedRequest Signed authorization request from backend
///
- (void)loginUserWithSignedRequest:(NSString * _Nonnull)signedRequest;
/// Legacy: Generate SDK authorization request (Objective-C compatible)
///
/// returns:
/// Authorization request string to be signed by backend
- (NSString * _Nonnull)generateSDKAuthorizationRequest SWIFT_WARN_UNUSED_RESULT;
/// Legacy: Check if authorization is valid (Objective-C compatible)
///
/// returns:
/// true if authorization token is valid
- (BOOL)isAuthorizationValid SWIFT_WARN_UNUSED_RESULT;
/// Legacy: Fetch configuration type (Objective-C compatible)
/// During migration: Calls Objective-C implementation
/// After migration: Uses new Swift configuration service
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param configType Configuration type (production or debug)
///
- (void)fetchConfigurationType:(EntrupyConfigType)configType;
/// Legacy: Start capture for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param item Dictionary containing item metadata
///
/// \param viewController View controller to present capture workflow
///
- (void)startCaptureForItem:(NSDictionary<NSString *, id> * _Nonnull)item viewController:(UIViewController * _Nonnull)viewController;
/// Legacy: Search submissions (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param pageCursor Cursor for pagination
///
/// \param filters Search filters array
///
/// \param startDate Start date (0 to omit)
///
/// \param endDate End date (0 to omit)
///
/// \param paginationLimit Number of items per page (max 25)
///
- (void)searchSubmissionsAt:(NSArray * _Nonnull)pageCursor filters:(NSArray * _Nonnull)filters startDate:(NSTimeInterval)startDate endDate:(NSTimeInterval)endDate paginationLimit:(NSInteger)paginationLimit;
/// Searches authentication items using date ranges and customizable filters.
/// Depending on the selected result mode, the response returns either paginated full item history or aggregate counts only.
/// This method provides a flexible way to query authentication results with various filter options.
/// The response is paginated and can be configured to return full result objects or just counts.
/// <h2>Response Model</h2>
/// The result dictionary can be decoded into <code>EntrupySearchItemsResult</code>:
/// <ul>
///   <li>
///     <code>metadata</code>: Contains <code>result_mode</code> (<code>.results</code> or <code>.countOnly</code>)
///   </li>
///   <li>
///     <code>total_count</code>: Total number of items matching the query
///   </li>
///   <li>
///     <code>item_count</code>: Number of items in the current page
///   </li>
///   <li>
///     <code>items</code>: Array of <code>EntrupyCaptureResult</code> objects (nil when using <code>.countOnly</code>)
///   </li>
///   <li>
///     <code>next_cursor</code>: Cursor for fetching the next page (nil if last page)
///   </li>
/// </ul>
/// <h2>Filter Examples</h2>
/// \code
/// filters: [
///     .status([.authentic, .underReview]),
///     .brands(["louis_vuitton", "gucci"]),
///     .category([.luxury, .apparel]),
///     .flag([.flagged])
/// ]
///
/// \endcode<h2>Usage Example</h2>
/// \code
/// guard EntrupyApp.sharedInstance().isAuthorizationValid() else { return }
///
/// // pagination state
/// var nextPageCursor: String? = nil
///
/// let query = EntrupySearchQuery(
///     dateRange: .last(days: 7),
///     filters: [
///         .status([.authentic]),
///         .category([.luxury, .apparel])
///     ],
///     resultMode: .results,  // or .countOnly
///     limit: 20,
///     cursor: nextPageCursor
/// )
///
/// EntrupyApp.sharedInstance().searchAuthenticationItems(query: query) { result, error in
///     guard let result = result,
///           let data = try? JSONSerialization.data(withJSONObject: result),
///           let searchResult = try? JSONDecoder().decode(EntrupySearchItemsResult.self, from: data)
///     else {
///         return
///     }
///     
///     print("Total: \(searchResult.total_count)")
///     if let items = searchResult.items {
///         // Process items
///     }
///
///    // Persist cursor for next page if available
///    nextPageCursor = searchResult.next_cursor
/// }
///
/// \endcodenote:
/// The product category filter is required for results.
/// For additional details on search and filtering, please refer to the  <a href="https://developer.entrupy.com/docs/mobile-sdks/ios/sdk-reference/direct-access-api-guides/programmatic-search-items">Entrupy iOS SDK Documentation</a>
/// \param query Search query with dateRange, filters, resultMode, limit, and cursor
///
/// \param completion Handler called with result dictionary or error
///
- (void)searchAuthenticationItemsWithQuery:(EntrupySearchQuery * _Nonnull)query completion:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))completion;
/// Legacy: Get flag details for result (Objective-C compatible)
/// This method calls the legacy Objective-C implementation which uses completion handlers.
/// For Swift callers, the dictionary is automatically bridged from NSDictionary to [AnyHashable: Any]?.
/// \param entrupyID Entrupy ID of the result
///
/// \param completionHandler Completion handler with details dictionary or error
///
- (void)getFlagDetailsForResultWithEntrupyID:(NSString * _Nonnull)entrupyID completionHandler:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))completionHandler;
/// Legacy: Set flag for result (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
/// \param flag true to set flag, false to clear
///
/// \param entrupyID Entrupy ID of the result
///
/// \param flagReasonId ID of the flag reason
///
/// \param message Optional message for the flag
///
- (void)setFlag:(BOOL)flag forResultWithEntrupyID:(NSString * _Nonnull)entrupyID flagReasonId:(NSString * _Nonnull)flagReasonId message:(NSString * _Nullable)message;
/// Legacy: Display detail view for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// The delegate set on the Swift facade is forwarded to the legacy implementation.
/// \param entrupyID Entrupy ID of the item
///
/// \param configuration View configuration options
///
- (void)displayDetailViewForItemWithEntrupyID:(NSString * _Nonnull)entrupyID withConfiguration:(EntrupyDetailViewConfiguration * _Nonnull)configuration;
/// Presents the Market Edge view for a specific authentication result.
/// @param entrupyID The Entrupy ID for the item to display.
/// @param viewConfiguration Configuration options, including:
/// - displayMarketGrade: Show/hide market grade
/// - displayMarketValue: Show/hide market value
/// - displayMarketMatch: Show/hide market match
/// - displayRegionSelection: Show/hide region selection
/// @note The view is Presented modally over the current top view controller.
/// \code
/// guard EntrupyApp.sharedInstance().isAuthorizationValid() else {
///     print("User not authorized. Cannot display Market Edge view.")
///     return
/// }
///
/// let configuration = EntrupyMarketEdgeViewConfiguration(
///     displayMarketGrade: true,
///     displayMarketValue: true,
///     displayMarketMatch: true,
///     displayRegionSelection: true
/// )
///
/// //Implement EntrupyMarketEdgeViewDelegate to receive presentation callbacks.
/// EntrupyApp.sharedInstance().marketEdgeViewDelegate = self
/// EntrupyApp.sharedInstance().displayMarketEdgeViewForItem(withEntrupyID: entrupyID, withConfiguration: configuration)
///
/// \endcode
- (void)displayMarketEdgeViewForItemWithEntrupyID:(NSString * _Nonnull)entrupyID withConfiguration:(EntrupyMarketEdgeViewConfiguration * _Nonnull)configuration;
/// Legacy: Display flag view for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// The delegate set on the Swift facade is forwarded to the legacy implementation.
/// \param entrupyID Entrupy ID of the result
///
- (void)displayFlagViewForItemWithEntrupyID:(NSString * _Nonnull)entrupyID;
/// Legacy: Start retake capture for item (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// The delegate set on the Swift facade is forwarded to the legacy implementation.
/// \param entrupyID Entrupy ID of the item requiring retake
///
- (void)startRetakeCaptureForItemWithEntrupyID:(NSString * _Nonnull)entrupyID;
/// Legacy: Search retakes (Objective-C compatible)
/// This method calls the legacy Objective-C implementation and propagates delegate callbacks.
/// Delegates are automatically forwarded via didSet when set on the Swift facade.
- (void)searchRetakes;
/// Fetches MarketEdge data for a given Entrupy ID.
/// This API retrieves MarketEdge information associated with an authentication result.
/// The response can be decoded into the SDK provided <code>EntrupyMarketEdge</code> model, which
/// represents a consolidated data for an item.
/// <code>EntrupyMarketEdge</code> includes:
/// important:
/// Ensure the user is logged in before invoking this API.
/// <ul>
///   <li>
///     <code>identifier</code>: Authentication identifiers for the item.
///   </li>
///   <li>
///     <code>market_grade</code>: Condition rating based on submitted images, including rating details,
///     item report information, and region-level descriptions (<code>EntrupyMarketGrade</code>).
///   </li>
///   <li>
///     <code>market_value</code>: Estimated market value derived from recent market data, including
///     price and currency (<code>EntrupyMarketValue</code>).
///   </li>
///   <li>
///     <code>market_match</code>: Recent marketplace listings similar to the submitted item, such as
///     brand, style, and price (<code>EntrupyMarketMatch</code>).
///   </li>
///   <li>
///     <code>disclaimer</code>: Disclaimer text associated with MarketGrade and MarketValue.
///   </li>
///   <li>
///     <code>error</code>: Error information when MarketEdge data is unavailable.
///   </li>
/// </ul>
/// <h3>Usage Example</h3>
/// \code
/// // Assign the delegate
/// entrupyApp.marketEdgeDelegate = self
///
/// // Request MarketEdge data
/// entrupyApp.fetchMarketEdgeForItem(withEntrupyID: entrupyID)
///
/// // Handle success
/// func didFetchMarketEdgeCompleteSuccessfully(
///     _ response: [AnyHashable: Any],
///     forEntrupyID entrupyID: String
/// ) {
///     do {
///         let data = try JSONSerialization.data(withJSONObject: response, options: [])
///         let marketEdge = try JSONDecoder().decode(EntrupyMarketEdge.self, from: data)
///
///           // Check for MarketEdge level error
///           if let error = marketEdge.error {
///             // Handle MarketEdge error
///             return
///         }
///
///         // Access MarketEdge properties
///         let identifier = marketEdge.identifier
///         let marketGrade = marketEdge.market_grade
///         let marketValue = marketEdge.market_value
///         let marketMatch = marketEdge.market_match
///         let disclaimer = marketEdge.disclaimer
///         
///
///         // Use the parsed data to populate UI or business logic
///     } catch {
///         // Handle decoding errors
///     }
/// }
///
/// // Handle failure
/// func didFetchMarketEdgeFailWithError(
///     _ errorCode: EntrupyErrorCode,
///     description: String,
///     localizedDescription: String,
///     forEntrupyID entrupyID: String
/// ) {
///     // Access the error code and localized description for failure cases
/// }
///
///
/// \endcode\param entrupyID The Entrupy authentication ID for which MarketEdge data should be fetched.
///
- (void)fetchMarketEdgeForItemWithEntrupyID:(NSString * _Nonnull)entrupyID;
/// Legacy: Cleanup user data (Objective-C compatible)
/// This method calls the legacy Objective-C implementation.
- (void)cleanup;
/// Legacy: Intercept application background URL session (Objective-C compatible)
/// During migration: Calls Objective-C implementation
/// \param application UIApplication instance
///
/// \param identifier URL session identifier
///
/// \param completionHandler Completion handler
///
- (void)interceptApplication:(UIApplication * _Nonnull)application handleEventsForBackgroundURLSession:(NSString * _Nonnull)identifier completionHandler:(void (^ _Nonnull)(void))completionHandler;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, EntrupyButtonBackgroundState, "EntrupyButtonBackgroundState", open) {
  EntrupyButtonBackgroundStateTapToCapture = 0,
  EntrupyButtonBackgroundStateBlurDetectionOn = 1,
  EntrupyButtonBackgroundStateMoveCloser = 2,
  EntrupyButtonBackgroundStateHandSteady = 3,
  EntrupyButtonBackgroundStateTapInsideToCapture = 4,
  EntrupyButtonBackgroundStateAutoCaptureActivated = 5,
  EntrupyButtonBackgroundStateNotDetected = 6,
  EntrupyButtonBackgroundStateNotInCenter = 7,
  EntrupyButtonBackgroundStateTooFar = 8,
  EntrupyButtonBackgroundStateMoveFar = 9,
};

@class NSCoder;
SWIFT_CLASS_NAMED("EntrupyCaptureButton")
@interface EntrupyCaptureButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setButtonBackgroundState:(enum EntrupyButtonBackgroundState)state;
- (enum EntrupyButtonBackgroundState)currentState SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC10EntrupySDK30EntrupyDetailViewConfiguration")
@interface EntrupyDetailViewConfiguration : NSObject
- (nonnull instancetype)initWithDisplayTimeline:(BOOL)displayTimeline displayUploadedImages:(BOOL)displayUploadedImages enableFlagging:(BOOL)enableFlagging enableItemDetailEdit:(BOOL)enableItemDetailEdit OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ObjcEntrupyEventName, "EntrupyEventName", open) {
  ObjcEntrupyEventNameCaptureStarted = 1,
  ObjcEntrupyEventNameCaptureSucceeded = 2,
  ObjcEntrupyEventNameCaptureFailed = 3,
  ObjcEntrupyEventNameCaptureCancelled = 4,
  ObjcEntrupyEventNameCaptureTimeout = 5,
  ObjcEntrupyEventNameRetakeStarted = 6,
  ObjcEntrupyEventNameRetakeSucceeded = 7,
  ObjcEntrupyEventNameRetakeCancelled = 8,
  ObjcEntrupyEventNameRetakeFailed = 9,
  ObjcEntrupyEventNameRetakeTimeout = 10,
  ObjcEntrupyEventNameAuthenticationBeginRequestSucceeded = 11,
  ObjcEntrupyEventNameAuthenticationCompleteRequestSucceeded = 12,
  ObjcEntrupyEventNameAuthenticationFetchRequestSucceeded = 13,
  ObjcEntrupyEventNameRetakeBatchRequestSucceeded = 14,
  ObjcEntrupyEventNameErrorOccurred = 15,
  ObjcEntrupyEventNameFullImageGuideButtonTap = 16,
  ObjcEntrupyEventNamePopupInstructionDoNotShowAgainCheckboxTap = 17,
  ObjcEntrupyEventNameRegionImageGuideButtonTap = 18,
  ObjcEntrupyEventNameFreshChatButtonTap = 19,
  ObjcEntrupyEventNameCertificateShareButtonTap = 20,
  ObjcEntrupyEventNameCertificateDownloadButtonTap = 21,
  ObjcEntrupyEventNameCertificateWebButtonTap = 22,
  ObjcEntrupyEventNameInvalidQrCode = 23,
  ObjcEntrupyEventNameGenericOcrSuccess = 24,
  ObjcEntrupyEventNameGenericOcrError = 25,
  ObjcEntrupyEventNameGenericOcrVerificationPopupShown = 26,
  ObjcEntrupyEventNameGenericOCRNoTextDetected = 27,
  ObjcEntrupyEventNameRfidScanError = 28,
  ObjcEntrupyEventNameRfidScanStarted = 29,
  ObjcEntrupyEventNameRfidScanSuccess = 30,
  ObjcEntrupyEventNameRfidScanCanceled = 31,
  ObjcEntrupyEventNameHistoryTimelineNoEventsFound = 32,
  ObjcEntrupyEventNameNotificationSignInSuccess = 33,
  ObjcEntrupyEventNameNotificationError = 34,
  ObjcEntrupyEventNameNotificationPushTokenRegistrationSuccess = 35,
  ObjcEntrupyEventNameNotificationSignInMaxRetryReached = 36,
  ObjcEntrupyEventNameNotificationJWTTokenExpired = 37,
  ObjcEntrupyEventNameUploadStarted = 38,
  ObjcEntrupyEventNameUploadSuccess = 39,
  ObjcEntrupyEventNameUploadError = 40,
  ObjcEntrupyEventNameMarketEdgeButtonTap = 41,
  ObjcEntrupyEventNameMarketGradeViewReportButtonTap = 42,
  ObjcEntrupyEventNameMarketMatchViewAllButtonTap = 43,
  ObjcEntrupyEventNameMarketMatchViewListingButtonTap = 44,
  ObjcEntrupyEventNameMarketEdgeRegionChangeButtonTap = 45,
  ObjcEntrupyEventNameMarketEdgeDisclaimerTap = 46,
  ObjcEntrupyEventNameMarketEdgeRefresh = 47,
  ObjcEntrupyEventNameMarketEdgeError = 48,
  ObjcEntrupyEventNameMarketEdgeStatus = 49,
  ObjcEntrupyEventNameMarketEdgeScreenExit = 50,
  ObjcEntrupyEventNameHistoryItemTap = 51,
  ObjcEntrupyEventNameInboxItemTap = 52,
  ObjcEntrupyEventNameViewCertificateButtonTap = 53,
  ObjcEntrupyEventNameViewTimelineButtonTap = 54,
  ObjcEntrupyEventNameViewDetailsButtonTap = 55,
  ObjcEntrupyEventNameNetworkLog = 56,
  ObjcEntrupyEventNameAuthenticationBeginRequestFailure = 57,
  ObjcEntrupyEventNameLogging = 58,
};

SWIFT_CLASS_NAMED("EntrupyLocalizationManager")
@interface ObjcEntrupyLocalizationManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10EntrupySDK34EntrupyMarketEdgeViewConfiguration")
@interface EntrupyMarketEdgeViewConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDisplayMarketGrade:(BOOL)displayMarketGrade displayMarketValue:(BOOL)displayMarketValue displayMarketMatch:(BOOL)displayMarketMatch displayRegionSelection:(BOOL)displayRegionSelection OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
SWIFT_CLASS("_TtC10EntrupySDK38EntrupyMarketGradeDetailViewController")
@interface EntrupyMarketGradeDetailViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@interface EntrupyMarketGradeDetailViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDelegate>
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UITableViewCell;
@interface EntrupyMarketGradeDetailViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC10EntrupySDK33EntrupyMarketGradeDetailViewModel")
@interface EntrupyMarketGradeDetailViewModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10EntrupySDK32EntrupyMarketMatchViewController")
@interface EntrupyMarketMatchViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface EntrupyMarketMatchViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@interface EntrupyMarketMatchViewController (SWIFT_EXTENSION(EntrupySDK)) <UITableViewDelegate>
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC10EntrupySDK18EntrupySearchQuery")
@interface EntrupySearchQuery : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_PROTOCOL("_TtP10EntrupySDK12EntrupyTheme_")
@protocol EntrupyTheme
@property (nonatomic, readonly, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nullable foregroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nullable borderColor;
@end

enum EntrupyZoomButtonBackgroundState : NSInteger;
SWIFT_CLASS_NAMED("EntrupyZoomButton")
@interface EntrupyZoomButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setButtonBackgroundState:(enum EntrupyZoomButtonBackgroundState)state;
- (enum EntrupyZoomButtonBackgroundState)currentBackgroundState SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, EntrupyZoomButtonBackgroundState, "EntrupyZoomButtonBackgroundState", open) {
  EntrupyZoomButtonBackgroundStateZoomIn = 0,
  EntrupyZoomButtonBackgroundStateZoomOut = 1,
};

@protocol ObjCSnapIQDelegate;
@class ObjCSnapIQResult;
SWIFT_CLASS_NAMED("SnapIQ")
@interface ObjCSnapIQ : NSObject
@property (nonatomic, readonly) BOOL isModelReady;
/// Delegate to receive detection results
@property (nonatomic, weak) id <ObjCSnapIQDelegate> _Nullable delegate;
/// Parameters:
/// <ul>
///   <li>
///     viewSize: The size of the view where boxes will be displayed
///   </li>
///   <li>
///     regionType: The type of region to detect and filter
///   </li>
///   <li>
///     isUltraWideEnabled: Whether ultra-wide lens is enabled for capture
///   </li>
///   <li>
///     completion: Callback to handle model loading results
///   </li>
/// </ul>
- (nonnull instancetype)initWithViewSize:(CGSize)viewSize regionType:(NSString * _Nonnull)regionType isUltraWideEnabled:(BOOL)isUltraWideEnabled completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion OBJC_DESIGNATED_INITIALIZER;
- (void)updateViewSize:(CGSize)newSize;
/// Process a camera frame and perform detection
/// \param sampleBuffer The camera frame buffer to process
///
///
/// returns:
/// A SnapIQResult containing the detected box and auto-capture analysis
- (ObjCSnapIQResult * _Nonnull)processFrameWithSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isRegionSupportedWithBrandName:(NSString * _Nonnull)brandName regionName:(NSString * _Nonnull)regionName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Delegate protocol for receiving SnapIQ detection results
SWIFT_PROTOCOL_NAMED("SnapIQDelegate")
@protocol ObjCSnapIQDelegate
- (void)didProcessFrameWithResult:(ObjCSnapIQResult * _Nonnull)result;
@end

/// Combined result containing both detected box and auto-capture analysis
SWIFT_CLASS_NAMED("SnapIQResult")
@interface ObjCSnapIQResult : NSObject
@property (nonatomic, readonly) BOOL shouldCapture;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly) float confidence;
@property (nonatomic, readonly) double fps;
@property (nonatomic, readonly) double inferenceTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
